apiVersion: install.tetrate.io/v1alpha1
kind: Tier1Gateway
metadata:
  name: tier1-gateway
  namespace: t1-bookinfo
spec:
  connectionDrainDuration: 5s
  kubeSpec:
    deployment:
      hpaSpec:
        maxReplicas: 10
        metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 75
              type: Utilization
          type: Resource
        minReplicas: 1
      strategy:
        rollingUpdate:
          maxUnavailable: 0
        type: RollingUpdate
    overlays:
    - apiVersion: apps/v1
      kind: Deployment
      name: tier1-gateway
      patches:
      - path: spec.template.spec.containers[-1]
        value:
          env:
          - name: LOCAL_HEALTHCHECK_PORT
            value: "8443"
          - name: REMOTE_HEALTHCHECK_PORT
            value: "443"
          - name: REGION
            value: centralus
          - name: RETRIES
            value: "3"
          - name: HEALTH_CHECK_INTERVAL
            value: 2s
          image: t1failovergw.azurecr.io/t1-healthcheck:srini-hs-image13
          name: t1-healthcheck
      - path: spec.template.spec.imagePullSecrets
        value:
        - name: regcred
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ports:
      - name: tls-istio-mtls
        port: 15443
        targetPort: 15443
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
      - name: http-t1-healthcheck
        port: 9443
        targetPort: 9443
      type: LoadBalancer
  revision: default
