apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: bookinfo-gateway
  namespace: bookinfo
spec:
  connectionDrainDuration: 5s
  kubeSpec:
    deployment:
      hpaSpec:
        maxReplicas: 10
        metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 75
              type: Utilization
          type: Resource
        minReplicas: 1
      strategy:
        rollingUpdate:
          maxUnavailable: 0
        type: RollingUpdate
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ports:
      - name: tls-istio-mtls
        port: 15443
        targetPort: 15443
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
      - name: http-t1-healthcheck
        port: 9443
        targetPort: 9443
      type: LoadBalancer
  revision: default
